# We use Typekit for some fonts, so ignore this suggestion
RemoteAsset:
  enabled: false
PaginationSize:
  max_size: 500
# Don't limit snippet nesting
NestedSnippet:
  enabled: false
# Seeing false positives from this
UnusedAssign:
  enabled: false
# False positives since we put theme code in a subdirectory
MissingTemplate:
  enabled: false
