name: Deploy/Dev

on:
  workflow_dispatch:

jobs:
  deploy:
    name: dev_deploy
    runs-on: ubuntu-latest
    steps:
      - name: "checkout release"
        uses: actions/checkout@v3
        with:
          ref: release-dev
      - name: "reset to release"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git fetch
          git checkout origin/release -- .
          git config --global user.email "office@castironcoding.com"
          git config --global user.name "Dev Deploy Action"
          git add .
          git diff --staged --quiet || git commit -m "[C] Deploy release branch - based on $(git rev-parse origin/release)"
          git push --force origin release-dev
