name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Theme Check
        uses: shopify/theme-check-action@v1
        with:
          theme_root: './shopify'
          token: ${{ github.token }}
          base: main

  lint:
    name: Lint CSS & JS Assets
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3

      - name: "Install Node"
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: "Install Yarn"
        run: |
          sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
          echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt-get update
          sudo apt-get install -y yarn

      - name: "Restore Node dependencies from cache"
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-module-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-module-cache-

      - name: "Install Node dependencies"
        env:
          NODE_ENV: development
        run: |
          yarn

      - name: "Lint Assets"
        run: |
          yarn lint:js && yarn lint:css
